server.port=8189
server.max-request-size=10240
server.max-response-size=10500
server.thread-pool-size=3
database.url=jdbc:postgresql://localhost:5432/otus-db
database.user=admin
database.password=password